Comparing --cache-min option
supreetpal/npmvsyarn pull request #2
Opened 2016-10-17 09:37 UTC by siddharthkp

- [x] Clean installs
- [x] Multiple runs
- [x] Added --cache-min

2016-10-17 09:55 UTC, supreetpal requested changes
Mostly looks great! I have left a few comments, which need to be resolved before I can merge. 
Please also move this PR to https://github.com/supreetpal/npmvsyarn/tree/feature/multiple-runs instead of master.

2016-10-17 09:55 UTC, supreetpal commented on bin/npmvsyarn.js
> -// Check if yarn exists, if not install it.
@siddharthkp you have accidentally removed this logic which checks if yarn already exists. If not, installs it.

2016-10-17 09:55 UTC, supreetpal commented on bin/npmvsyarn.js
> +// Install module using yarn add.
This comment is not relevant over here. Should be moved to below rm node_modules.

2016-10-17 09:55 UTC, supreetpal commented on bin/npmvsyarn.js
> +sh.exec('rm node_modules', {silent: true});
rm -rf should be a better option.

2016-10-17 09:55 UTC, supreetpal commented on bin/npmvsyarn.js
> +sh.exec('rm node_modules', {silent: true});
rm -rf

2016-10-17 09:57 UTC, supreetpal commented
rm -rf node_modules is also not a safe command to run. It will remove the existing node_modules folder of the user where this command is run. We need to save the existing one in temp then move it back later. Instead of simple clearing it.

2016-10-19 05:44 UTC, siddharthkp commented
@supreetpal I didn't expect that you would want to merge this 😄
Was just showing the code for comparison

Although, if you're interested I can help you out with the other features

2016-12-13 07:30 UTC, closed without merging